apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookcatalog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookcatalog
  template:
    metadata:
      labels:
        app: bookcatalog
    spec:
      containers:
      - name: bookcatalog
        image: bookcatalog:1.0
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: bookcatalog-service
spec:
  type: NodePort
  selector:
    app: bookcatalog
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30002
