name: Build Task Manager

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        ls -la
        docker build . --file applications/taskmanager/Dockerfile --tag taskmanager:latest
